title: Play notes in a loop
hero_image: images/banner.png
description: notes-in-loop description
version: 4
listed: false
copyedit: false
last_tested: "2022-03-10"
steps:
  - title: Introduction
  - title: Step title
  - title: What next?
