title: Jouer des notes en boucle
hero_image: images/banner.png
description: Jouer des notes en boucle
version: 4
listed: false
copyedit: false
last_tested: "2022-03-10"
steps:
  - 
    title: Jouer des notes en boucle
